// WebCurveEditor.cpp — JUCE 8 WebBrowserComponent-based plugin editor.
//
// The HTML/JS bundle (dist/index.html + dist/bundle.js) is compiled into
// BinaryData by CMake's juce_add_binary_data(DrawnCurveWebUI …).
// The resource provider serves those byte arrays to WKWebView without a server.

#include "WebCurveEditor.h"
#include <BinaryDataWebUI.h>      // generated by juce_add_binary_data(DrawnCurveWebUI …)

// ── Helpers ───────────────────────────────────────────────────────────────────

// Build a var::Object (JSON object) from key-value pairs for event payloads.
static juce::var makeObj (std::initializer_list<std::pair<juce::String, juce::var>> pairs)
{
    auto obj = std::make_unique<juce::DynamicObject>();
    for (auto& [k, v] : pairs)
        obj->setProperty (k, v);
    return juce::var (obj.release());
}

// ── Resource provider ─────────────────────────────────────────────────────────
// Serves index.html and bundle.js from the BinaryData arrays generated by CMake.

std::optional<juce::WebBrowserComponent::Resource>
WebCurveEditor::provideResource (const juce::String& path)
{
    struct Entry { const char* data; int size; juce::String mime; };

    static const std::array<std::pair<const char*, Entry>, 3> table {{
        { "/",           { BinaryData::index_html,
                           BinaryData::index_htmlSize,
                           "text/html; charset=utf-8" } },
        { "/index.html", { BinaryData::index_html,
                           BinaryData::index_htmlSize,
                           "text/html; charset=utf-8" } },
        { "/bundle.js",  { BinaryData::bundle_js,
                           BinaryData::bundle_jsSize,
                           "application/javascript" } },
    }};

    for (auto& [key, entry] : table)
    {
        if (path == key)
        {
            std::vector<std::byte> bytes (static_cast<std::size_t> (entry.size));
            std::memcpy (bytes.data(), entry.data, static_cast<std::size_t> (entry.size));
            return juce::WebBrowserComponent::Resource { std::move (bytes), entry.mime };
        }
    }
    return std::nullopt;
}

// ── Options builder ───────────────────────────────────────────────────────────

juce::WebBrowserComponent::Options WebCurveEditor::buildOptions (WebCurveEditor* owner)
{
    using juce::WebBrowserComponent;
    using juce::var;
    using juce::Array;

    return WebBrowserComponent::Options{}
        .withResourceProvider ([](const juce::String& path)
            { return WebCurveEditor::provideResource (path); },
            WebBrowserComponent::getResourceProviderRoot())
        .withNativeIntegrationEnabled()
       #if JUCE_MAC
        // macOS only: prevent JUCE navigating to about:blank when isShowing()
        // returns false.  In Logic Pro's out-of-process AUv3 host the view is
        // attached via RemoteViewService (ViewBridge XPC), so the WKWebView is
        // considered "hidden" during the entire initialisation window.  Without
        // this option, checkWindowAssociation() fires repeatedly and keeps
        // overwriting our juce:// URL with about:blank → blank plugin GUI.
        //
        // NOT applied on iOS: it prevents the system from managing WKWebView's
        // lifecycle, fights iOS's memory manager, and causes the "Could not
        // create a sandbox extension" / WebContent-process-unresponsive crash
        // seen on iPad.  iOS Standalone doesn't have the ViewBridge race so
        // the option is unnecessary there.
        .withKeepPageLoadedWhenBrowserIsHidden()
       #endif

        // ── JS → C++: UI signals ──────────────────────────────────────────────
        // "log" — diagnostic console.log mirror from JS
        .withEventListener ("log", [] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto level = args[0]["level"].toString();
            const auto msg   = args[0]["msg"].toString();
            std::fprintf (stderr, "[js:%s] %s\n",
                          level.toRawUTF8(), msg.toRawUTF8());
            std::fflush (stderr);
        })

        // "uiReady" — page has loaded and wants the initial state snapshot
        .withEventListener ("uiReady", [owner] (const Array<var>&)
        {
            owner->pageReady = true;
            juce::MessageManager::callAsync ([owner]
            {
                // Force every lane into "follow global transport" mode.  The
                // WebUI exposes only the global direction / speed sliders,
                // and the saved APVTS state may carry useGlobalPlayback=false
                // from a previous run (or from the native editor) — which
                // would silently shadow the global controls.  Setting this
                // here on every page-load makes the WebUI's "global only"
                // model the source of truth.
               #if defined(DC_HAVE_PER_LANE_PLAYBACK_PARAMS)
                for (int L = 0; L < kMaxLanes; ++L)
                {
                    if (auto* p = dynamic_cast<juce::AudioParameterBool*> (
                                      owner->proc.apvts.getParameter (
                                          laneParam (L, ParamID::useGlobalPlayback))))
                        *p = true;
                }
               #endif
                owner->sendStateSnapshot();
                // Start the engine playing.  Without this, a fresh plugin
                // instance has _isPlaying=false → processLane returns early
                // → no MIDI output, no quantization, despite a valid
                // snapshot being in place.  The user can still toggle via
                // the transport; this is just a sane default for the
                // standalone & for hosts that don't drive the param.
                owner->proc.setPlaying (true);
            });
        })

        // "setParam" — { id: "l0_ccNumber", value: 0..1 (host-normalised) }
        // Use this when the JS side already pre-normalises (LANE_MAP + GLOBAL_PARAM_MAP).
        .withEventListener ("setParam", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto& obj = args[0];
            const auto id    = obj["id"].toString();
            const float val  = static_cast<float> (static_cast<double> (obj["value"]));
            if (auto* p = owner->proc.apvts.getParameter (id))
                p->setValueNotifyingHost (val);
        })

        // "setParamActual" — { id, value: actual-domain value }
        // The C++ side does the 0..1 conversion through the parameter's own
        // NormalisableRange — so JS doesn't need to know about skew factors
        // (e.g. playbackSpeed has skew=0.5 — a log curve we don't want to
        // duplicate on the JS side).
        .withEventListener ("setParamActual", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto& obj = args[0];
            const auto  id  = obj["id"].toString();
            const float val = static_cast<float> (static_cast<double> (obj["value"]));
            if (auto* p = dynamic_cast<juce::RangedAudioParameter*> (
                              owner->proc.apvts.getParameter (id)))
                p->setValueNotifyingHost (p->convertTo0to1 (val));
        })

        // "setCurve" — { lane: 0, data: [0.0, …, 1.0] (256 floats or null) }
        .withEventListener ("setCurve", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto& obj = args[0];
            const int lane  = static_cast<int> (obj["lane"]);
            const auto& arr = *obj["data"].getArray();

            if (arr.isEmpty())
            {
                owner->proc.clearSnapshot (lane);
            }
            else
            {
                auto snap = std::make_unique<float[]> (256);
                for (int i = 0; i < 256; ++i)
                    snap[static_cast<std::size_t> (i)] = static_cast<float> (static_cast<double> (arr[i]));
                owner->proc.setSnapshotFromArray (lane, snap.get(), 256);
            }
        })

        // "setFocus" — { lane: N }
        .withEventListener ("setFocus", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            // No-op for now — focus is UI-only in the WebView version.
            (void) owner;
        })

        // "setPlaying" — { playing: true/false }
        // No APVTS param called "playing" exists; the engine's _isPlaying flag
        // is set directly by DrawnCurveProcessor::setPlaying().  The previous
        // code looked up a non-existent parameter, so getParameter() returned
        // null and the engine stayed at its default _isPlaying=false — which
        // caused processLane() to early-out and swallow every per-lane render
        // (no audio out, no quantization, no Note-Ons).
        .withEventListener ("setPlaying", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const bool playing = static_cast<bool> (args[0]["playing"]);
            owner->proc.setPlaying (playing);
        })

        // "clearLane" — { lane: N }
        .withEventListener ("clearLane", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const int lane = static_cast<int> (args[0]["lane"]);
            owner->proc.clearSnapshot (lane);
        })

        // "addLane" — {}
        .withEventListener ("addLane", [owner] (const Array<var>&)
        {
            if (owner->proc.activeLaneCount < kMaxLanes)
            {
                ++owner->proc.activeLaneCount;
                owner->sendStateSnapshot();
            }
        })

        // "removeLane" — { lane: N }
        .withEventListener ("removeLane", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const int lane = static_cast<int> (args[0]["lane"]);
            owner->proc.deleteLane (lane);
            owner->sendStateSnapshot();
        })

        // "panic" — {} — All Notes Off on every channel; resets engine dedup state
        .withEventListener ("panic", [owner] (const Array<var>&)
        {
            owner->proc.sendPanic();
        })

        // "beginTeach" — { lane } — arm the lane to capture the next incoming CC#.
        // The engine isolates the lane (soloLane), waits for one CC message,
        // writes it to l<n>_ccNumber, then clears the pending flag automatically.
        // The paramChange echo for ccNumber tells the JS side to exit teach mode.
        .withEventListener ("beginTeach", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const int lane = static_cast<int> (args[0]["lane"]);
            owner->proc.beginTeach (lane);
        })

        // "cancelTeach" — {} — disarm without changing the CC number.
        .withEventListener ("cancelTeach", [owner] (const Array<var>&)
        {
            owner->proc.cancelTeach();
        })

        // "beginRecord" — { lane: N } — arm a lane for MIDI input recording.
        // The audio thread will buffer incoming MIDI messages; the timer drains
        // them and forwards to JS as "midiIn" events for the JS recorder.
        .withEventListener ("beginRecord", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const int lane = static_cast<int> (args[0]["lane"]);
            owner->proc.beginRecord (lane);
        })

        // "stopRecord" — {} — disarm; audio thread stops buffering.
        .withEventListener ("stopRecord", [owner] (const Array<var>&)
        {
            owner->proc.stopRecord();
        });
}

// ── Constructor / Destructor ──────────────────────────────────────────────────

WebCurveEditor::WebCurveEditor (DrawnCurveProcessor& p)
    : AudioProcessorEditor (p),
      proc (p),
      webView (buildOptions (this))
{
    addAndMakeVisible (webView);
    setSize (1024, 768);
    setResizable (true, false);

    // Listen to all APVTS parameters so we can forward changes to JS.
    const auto& params = proc.apvts.processor.getParameters();
    for (auto* param : params)
    {
        if (auto* pwid = dynamic_cast<juce::AudioProcessorParameterWithID*> (param))
        {
            proc.apvts.addParameterListener (pwid->paramID, this);
            listenedParams.add (pwid->paramID);
        }
    }

    // ── Standalone MIDI output ────────────────────────────────────────────────
    // Mirror the native editor's behaviour: when running as a standalone app,
    // create a virtual MIDI source called "DrawnQurve" and register it with
    // the processor.  Without this the engine's MIDI emission has nowhere to
    // go (both _virtualMidiOut and _directMidiOut stay null in the timer
    // path), which silently discards every Note On / CC / PB the engine
    // generates — that's what "no quantization" looked like from the outside.
    if (juce::JUCEApplicationBase::isStandaloneApp())
    {
        virtualMidiPort = juce::MidiOutput::createNewDevice ("DrawnQurve");
        if (virtualMidiPort != nullptr)
            proc.setVirtualMidiOutput (virtualMidiPort.get());
    }

    // Initial navigation attempt.  navigateIfNeeded() also fires from
    // parentHierarchyChanged() which is the reliable hook for AUv3 hosts
    // (Logic Pro, GarageBand) where the view is parented AFTER construction.
    juce::MessageManager::callAsync ([this] { navigateIfNeeded(); });

    // Start phase heartbeat at 30 Hz
    startTimer (33);
}

// ── Navigation helpers ────────────────────────────────────────────────────────

void WebCurveEditor::navigateIfNeeded()
{
    if (pageNavigated)
        return;
    pageNavigated = true;
    webView.goToURL (juce::WebBrowserComponent::getResourceProviderRoot());
}

// Called by JUCE whenever this component is added to (or moved within) a
// parent component's hierarchy.  In AUv3 the host embeds the plugin view
// AFTER the AudioProcessorEditor constructor returns, so this is the
// earliest reliable moment to start the WKWebView navigation without risking
// a silent no-op from a not-yet-parented WebView.
void WebCurveEditor::parentHierarchyChanged()
{
    AudioProcessorEditor::parentHierarchyChanged();
    if (getParentComponent() != nullptr)
        navigateIfNeeded();
}

WebCurveEditor::~WebCurveEditor()
{
    stopTimer();
    for (const auto& id : listenedParams)
        proc.apvts.removeParameterListener (id, this);

    // Detach the virtual MIDI port from the processor BEFORE the unique_ptr
    // resets, so the audio/timer thread never reads a dangling pointer.
    proc.setVirtualMidiOutput (nullptr);
    proc.setDirectMidiOutput  (nullptr);
}

// ── Layout ────────────────────────────────────────────────────────────────────

void WebCurveEditor::resized()
{
    webView.setBounds (getLocalBounds());
}

// ── Phase timer ───────────────────────────────────────────────────────────────

void WebCurveEditor::timerCallback()
{
    if (! pageReady)
        return;

    const float phase   = proc.currentPhase();
    const bool playing  = proc.isPlaying();

    const bool phaseChanged   = std::abs (phase - lastSentPhase) >= 0.001f;
    const bool playingChanged = playing != lastEmittedPlaying;

    // ── MIDI recording drain ──────────────────────────────────────────────────
    // Drain captured MIDI events on every timer tick, regardless of whether
    // phase is moving.  This matters for recording while the host is paused,
    // or in free-running mode at very low speed.  The drain was previously
    // inside the phase-change guard, causing events to be silently lost
    // whenever the transport was still.
    const auto captured = proc.drainMidiCapture();
    for (const auto& ev : captured)
    {
        // "ms" is the millisecond offset from the moment beginRecord() was
        // called, computed on the audio thread.  JS uses it as the note
        // timestamp so positions stay accurate even when the 30 Hz drain
        // timer fires late or in bursts.
        webView.emitEventIfBrowserIsVisible ("midiIn",
            makeObj ({ { "lane",   ev.lane },
                       { "status", (int) ev.status },
                       { "data1",  (int) ev.d1 },
                       { "data2",  (int) ev.d2 },
                       { "ms",     (juce::int64) ev.ms } }));
    }

    // Always emit when playing state changes (so JS can pause its demo loop);
    // also emit when phase moves meaningfully.
    if (! phaseChanged && ! playingChanged)
        return;

    lastSentPhase      = phase;
    lastEmittedPlaying = playing;

    juce::Array<juce::var> lanePhases;
    for (int L = 0; L < proc.activeLaneCount; ++L)
        lanePhases.add (proc.currentPhaseForLane (L));

    webView.emitEventIfBrowserIsVisible ("phase",
        makeObj ({ { "phase",   phase },
                   { "lanes",   juce::var (lanePhases) },
                   { "playing", playing } }));
}

// ── Parameter listener ────────────────────────────────────────────────────────

void WebCurveEditor::parameterChanged (const juce::String& paramID, float newValue)
{
    if (! pageReady)
        return;

    // Forward every parameter change to JS in real time.
    // Keep the object on the message thread (parameterChanged may be called
    // from the audio thread on some hosts).
    juce::MessageManager::callAsync ([this, paramID, newValue]
    {
        if (! pageReady)
            return;
        webView.emitEventIfBrowserIsVisible ("paramChange",
            makeObj ({ { "id", paramID }, { "value", newValue } }));

        // Rebuild the engine snapshot(s) for the affected lane(s).  APVTS
        // atomics update on setValueNotifyingHost, but the audio thread reads
        // from a separate LaneSnapshot struct that's only refreshed by
        // updateLaneSnapshot().  Per-lane params hit one lane; global sync
        // params (syncEnabled / syncBeats) change loop length, so every lane
        // needs a refresh.
        if (paramID == ParamID::syncEnabled || paramID == ParamID::syncBeats)
        {
            for (int L = 0; L < proc.activeLaneCount; ++L)
                proc.updateLaneSnapshot (L);
        }
        else if (paramID == ParamID::scaleRoot || paramID == ParamID::scaleMask
              || paramID == ParamID::scaleMode)
        {
            // Global scale params — push the new ScaleConfig to the engine for
            // every active lane so Note-mode quantization takes effect immediately.
            proc.updateAllLaneScales();
        }
        else if (paramID.startsWith ("l"))
        {
            const int sep = paramID.indexOfChar ('_');
            if (sep > 1)
            {
                const int lane = paramID.substring (1, sep).getIntValue();
                if (lane >= 0 && lane < kMaxLanes)
                {
                    const juce::String suffix = paramID.substring (sep + 1);

                    // Scale params must reach the engine even when no curve has
                    // been drawn yet.  updateLaneSnapshot() returns early if
                    // _laneSnaps[lane] is null, so calling it for scale changes
                    // silently drops the update.  Route directly to the engine.
                    if (suffix == ParamID::scaleRoot || suffix == ParamID::scaleMask)
                        proc.updateEngineScale (lane);
                    else
                        proc.updateLaneSnapshot (lane);
                        // Note: do NOT call resetLanePlayhead here for loopMode.
                        // The one-shot sentinel (playheadSeconds == -1) must hold
                        // until an explicit global reset (play button / host transport
                        // restart).  Calling resetLane from parameterChanged risks
                        // clearing the sentinel on a delayed APVTS echo — which would
                        // restart the lane and produce the "briefly pauses then loops"
                        // symptom.  If the user wants a retrigger they press Play.
                }
            }
        }
    });
}

// ── State snapshot ────────────────────────────────────────────────────────────

void WebCurveEditor::sendStateSnapshot()
{
    // Build a complete state object and emit it so the JS can initialise
    // its React state from real APVTS values instead of the demo sine curves.

    juce::var lanesArr (juce::Array<juce::var>{});
    auto& lanesArrRef = *lanesArr.getArray();

    for (int L = 0; L < proc.activeLaneCount; ++L)
    {
        auto lane = std::make_unique<juce::DynamicObject>();

        lane->setProperty ("id",    L);
        lane->setProperty ("name",  "Lane " + juce::String (L + 1));

        // APVTS helpers.
        // getRawParameterValue returns ACTUAL values (not 0-1 normalised):
        //   AudioParameterChoice → choice index (0, 1, 2 …)
        //   AudioParameterInt    → integer value in its declared range
        //   AudioParameterFloat  → float in its declared range (smoothing/minOut/maxOut are 0-1)
        //   AudioParameterBool   → 0.0f or 1.0f
        const auto raw = [&] (const juce::String& suffix) -> float {
            if (auto* p = proc.apvts.getRawParameterValue (laneParam (L, suffix)))
                return p->load();
            jassertfalse;   // parameter ID not registered — check laneParam() format
            return 0.0f;
        };

        // (globalRaw helper removed — scaleRoot/scaleMask are now per-lane params)

        static const char* kTargets[4] = { "CC", "Aftertouch", "PitchBend", "Note" };
        const int msgType = juce::jlimit (0, 3, static_cast<int> (raw ("msgType")));
        lane->setProperty ("target",       kTargets[msgType]);
        lane->setProperty ("targetDetail", static_cast<int> (raw ("ccNumber")));   // 0-127
        lane->setProperty ("channel",      static_cast<int> (raw ("midiChannel")));// 1-16
        lane->setProperty ("smooth",       raw ("smoothing"));                     // 0-1
        lane->setProperty ("rangeMin",     raw ("minOutput"));                     // 0-1
        lane->setProperty ("rangeMax",     raw ("maxOutput"));                     // 0-1
        lane->setProperty ("velocity",     static_cast<int> (raw ("noteVelocity")));// 1-127
        lane->setProperty ("enabled",      raw ("enabled") > 0.5f);
        // Playback behaviour — loop mode and legato tie.
        lane->setProperty ("oneShot",     raw (ParamID::loopMode)    > 0.5f);  // false=loop, true=one-shot
        lane->setProperty ("legato",      raw (ParamID::legatoMode)  > 0.5f);  // Note mode only
        lane->setProperty ("phaseOffset", raw (ParamID::phaseOffset));          // 0-100 percent
        // Per-lane quantization (mirrors xQuantize/yQuantize/xDivisions/yDivisions APVTS).
        lane->setProperty ("quantizeX",    raw ("xQuantize") > 0.5f);
        lane->setProperty ("quantizeY",    raw ("yQuantize") > 0.5f);
        lane->setProperty ("xDivisions",   static_cast<int> (raw ("xDivisions")));   // 2-32
        lane->setProperty ("yDivisions",   static_cast<int> (raw ("yDivisions")));   // 2-24
        // Per-lane scale (scaleMode is a JS-side UI concept — engine uses mask directly).
        lane->setProperty ("scaleRoot",    static_cast<int> (raw (ParamID::scaleRoot)));  // 0-11
        lane->setProperty ("scaleMask",    static_cast<int> (raw (ParamID::scaleMask)));  // 0-4095
        lane->setProperty ("scaleId",      "chromatic");   // JS resolves from mask via recognizeScaleId()

#if defined(DC_HAVE_PER_LANE_PLAYBACK_PARAMS)
        // Per-lane playback overrides (surfaced in the shape well as "Override Transport").
        // useGlobalPlayback defaults to true so lanes follow the global transport until
        // the user explicitly enables per-lane direction/speed in the shape well.
        lane->setProperty ("useGlobalPlayback", raw (ParamID::useGlobalPlayback) > 0.5f);
        lane->setProperty ("laneSpeedMul",      raw (ParamID::laneSpeedMul));      // 0.25 – 4.0
        // laneDirection: APVTS choice index 0/1/2 → JS string 'fwd'/'rev'/'pp'
        static const char* const kLaneDirNames[] = { "fwd", "rev", "pp" };
        const int ldIdx = juce::jlimit (0, 2, static_cast<int> (raw (ParamID::laneDirection)));
        lane->setProperty ("laneDirection", kLaneDirNames[ldIdx]);
#else
        lane->setProperty ("useGlobalPlayback", true);
        lane->setProperty ("laneSpeedMul",      1.0f);
        lane->setProperty ("laneDirection",     "fwd");
#endif

        // Curve data (Float32Array → JSON array of 256 floats)
        if (proc.hasCurve (L))
        {
            juce::var curveArr (juce::Array<juce::var>{});
            auto& ref = *curveArr.getArray();
            ref.resize (256);
            const auto table = proc.getCurveTable (L);
            for (int i = 0; i < 256; ++i)
                ref.set (i, table[static_cast<std::size_t> (i)]);
            lane->setProperty ("curve", curveArr);
        }
        else
        {
            lane->setProperty ("curve", juce::var());   // null
        }

        lanesArrRef.add (juce::var (lane.release()));
    }

    // Pull global transport state from APVTS so the JS UI starts in sync with
    // what the engine actually believes.  Hard-coding these created a silent
    // mismatch: the UI thought sync was on while APVTS::syncEnabled was off,
    // so the beats slider wrote to syncBeats but the engine kept using the
    // free-running 1 s loop length until the user toggled sync off→on.
    const bool   apvtsSyncOn   = proc.apvts.getRawParameterValue (ParamID::syncEnabled)->load() > 0.5f;
    const float  apvtsBeats    = proc.apvts.getRawParameterValue (ParamID::syncBeats)->load();
    const float  apvtsSpeed    = proc.apvts.getRawParameterValue (ParamID::playbackSpeed)->load();
    const int    apvtsDirIdx   = juce::jlimit (0, 2, static_cast<int> (
                                     proc.apvts.getRawParameterValue (ParamID::playbackDirection)->load()));
    static const char* const kDirNames[] = { "fwd", "rev", "pp" };

    const auto snap = makeObj ({
        { "lanes",           lanesArr },
        { "activeLaneCount", proc.activeLaneCount },
        { "phase",           proc.currentPhase() },
        { "playing",         true },
        { "direction",       kDirNames[apvtsDirIdx] },
        { "syncOn",          apvtsSyncOn },
        { "beats",           apvtsBeats },
        { "speed",           apvtsSpeed },
        { "focus",           0 },
    });

    webView.emitEventIfBrowserIsVisible ("stateSnapshot", snap);
}

void WebCurveEditor::sendCurveData (int lane)
{
    if (!proc.hasCurve (lane)) return;

    juce::var arr (juce::Array<juce::var>{});
    auto& ref = *arr.getArray();
    ref.resize (256);
    const auto table = proc.getCurveTable (lane);
    for (int i = 0; i < 256; ++i)
        ref.set (i, table[static_cast<std::size_t> (i)]);

    webView.emitEventIfBrowserIsVisible ("curveData",
        makeObj ({ { "lane", lane }, { "data", arr } }));
}
