// WebCurveEditor.cpp — JUCE 8 WebBrowserComponent-based plugin editor.
//
// The HTML/JS bundle (dist/index.html + dist/bundle.js) is compiled into
// BinaryData by CMake's juce_add_binary_data(DrawnCurveWebUI …).
// The resource provider serves those byte arrays to WKWebView without a server.

#include "WebCurveEditor.h"
#include <BinaryDataWebUI.h>      // generated by juce_add_binary_data(DrawnCurveWebUI …)

// ── Helpers ───────────────────────────────────────────────────────────────────

// Build a var::Object (JSON object) from key-value pairs for event payloads.
static juce::var makeObj (std::initializer_list<std::pair<juce::String, juce::var>> pairs)
{
    auto obj = std::make_unique<juce::DynamicObject>();
    for (auto& [k, v] : pairs)
        obj->setProperty (k, v);
    return juce::var (obj.release());
}

// ── Resource provider ─────────────────────────────────────────────────────────
// Serves index.html and bundle.js from the BinaryData arrays generated by CMake.

std::optional<juce::WebBrowserComponent::Resource>
WebCurveEditor::provideResource (const juce::String& path)
{
    struct Entry { const char* data; int size; juce::String mime; };

    static const std::array<std::pair<const char*, Entry>, 3> table {{
        { "/",           { BinaryData::index_html,
                           BinaryData::index_htmlSize,
                           "text/html; charset=utf-8" } },
        { "/index.html", { BinaryData::index_html,
                           BinaryData::index_htmlSize,
                           "text/html; charset=utf-8" } },
        { "/bundle.js",  { BinaryData::bundle_js,
                           BinaryData::bundle_jsSize,
                           "application/javascript" } },
    }};

    for (auto& [key, entry] : table)
    {
        if (path == key)
        {
            std::vector<std::byte> bytes (static_cast<std::size_t> (entry.size));
            std::memcpy (bytes.data(), entry.data, static_cast<std::size_t> (entry.size));
            return juce::WebBrowserComponent::Resource { std::move (bytes), entry.mime };
        }
    }
    return std::nullopt;
}

// ── Options builder ───────────────────────────────────────────────────────────

juce::WebBrowserComponent::Options WebCurveEditor::buildOptions (WebCurveEditor* owner)
{
    using juce::WebBrowserComponent;
    using juce::var;
    using juce::Array;

    return WebBrowserComponent::Options{}
        .withResourceProvider ([](const juce::String& path)
            { return WebCurveEditor::provideResource (path); },
            WebBrowserComponent::getResourceProviderRoot())
        .withNativeIntegrationEnabled()

        // ── JS → C++: UI signals ──────────────────────────────────────────────
        // "log" — diagnostic console.log mirror from JS
        .withEventListener ("log", [] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto level = args[0]["level"].toString();
            const auto msg   = args[0]["msg"].toString();
            std::fprintf (stderr, "[js:%s] %s\n",
                          level.toRawUTF8(), msg.toRawUTF8());
            std::fflush (stderr);
        })

        // "uiReady" — page has loaded and wants the initial state snapshot
        .withEventListener ("uiReady", [owner] (const Array<var>&)
        {
            owner->pageReady = true;
            juce::MessageManager::callAsync ([owner] { owner->sendStateSnapshot(); });
        })

        // "setParam" — { id: "lane0_ccNumber", value: 0.5 }
        .withEventListener ("setParam", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto& obj = args[0];
            const auto id    = obj["id"].toString();
            const float val  = static_cast<float> (static_cast<double> (obj["value"]));
            if (auto* p = owner->proc.apvts.getParameter (id))
                p->setValueNotifyingHost (val);
        })

        // "setCurve" — { lane: 0, data: [0.0, …, 1.0] (256 floats or null) }
        .withEventListener ("setCurve", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto& obj = args[0];
            const int lane  = static_cast<int> (obj["lane"]);
            const auto& arr = *obj["data"].getArray();

            if (arr.isEmpty())
            {
                owner->proc.clearSnapshot (lane);
            }
            else
            {
                auto snap = std::make_unique<float[]> (256);
                for (int i = 0; i < 256; ++i)
                    snap[static_cast<std::size_t> (i)] = static_cast<float> (static_cast<double> (arr[i]));
                owner->proc.setSnapshotFromArray (lane, snap.get(), 256);
            }
        })

        // "setFocus" — { lane: N }
        .withEventListener ("setFocus", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            // No-op for now — focus is UI-only in the WebView version.
            (void) owner;
        })

        // "setPlaying" — { playing: true/false }
        .withEventListener ("setPlaying", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const bool playing = static_cast<bool> (args[0]["playing"]);
            if (auto* p = dynamic_cast<juce::AudioParameterBool*> (
                              owner->proc.apvts.getParameter ("playing")))
                *p = playing;
        })

        // "clearLane" — { lane: N }
        .withEventListener ("clearLane", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const int lane = static_cast<int> (args[0]["lane"]);
            owner->proc.clearSnapshot (lane);
        })

        // "addLane" — {}
        .withEventListener ("addLane", [owner] (const Array<var>&)
        {
            if (owner->proc.activeLaneCount < kMaxLanes)
            {
                ++owner->proc.activeLaneCount;
                owner->sendStateSnapshot();
            }
        })

        // "removeLane" — { lane: N }
        .withEventListener ("removeLane", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const int lane = static_cast<int> (args[0]["lane"]);
            owner->proc.deleteLane (lane);
            owner->sendStateSnapshot();
        });
}

// ── Constructor / Destructor ──────────────────────────────────────────────────

WebCurveEditor::WebCurveEditor (DrawnCurveProcessor& p)
    : AudioProcessorEditor (p),
      proc (p),
      webView (buildOptions (this))
{
    addAndMakeVisible (webView);
    setSize (1024, 768);
    setResizable (true, false);

    // Listen to all APVTS parameters so we can forward changes to JS.
    const auto& params = proc.apvts.processor.getParameters();
    for (auto* param : params)
    {
        if (auto* p = dynamic_cast<juce::AudioProcessorParameterWithID*> (param))
        {
            proc.apvts.addParameterListener (p->paramID, this);
            listenedParams.add (p->paramID);
        }
    }

    // Navigate to the resource provider root — triggers "uiReady" from JS
    // once the page has loaded and the bridge is initialised.
    webView.goToURL (juce::WebBrowserComponent::getResourceProviderRoot());

    // Start phase heartbeat at 30 Hz
    startTimer (33);
}

WebCurveEditor::~WebCurveEditor()
{
    stopTimer();
    for (const auto& id : listenedParams)
        proc.apvts.removeParameterListener (id, this);
}

// ── Layout ────────────────────────────────────────────────────────────────────

void WebCurveEditor::resized()
{
    webView.setBounds (getLocalBounds());
}

// ── Phase timer ───────────────────────────────────────────────────────────────

void WebCurveEditor::timerCallback()
{
    if (! pageReady)
        return;

    const float phase = proc.currentPhase();   // exposed on DrawnCurveProcessor

    // Only emit if phase has moved meaningfully (avoids flooding when paused)
    if (std::abs (phase - lastSentPhase) < 0.001f)
        return;
    lastSentPhase = phase;

    webView.emitEventIfBrowserIsVisible ("phase", makeObj ({ { "phase", phase } }));
}

// ── Parameter listener ────────────────────────────────────────────────────────

void WebCurveEditor::parameterChanged (const juce::String& paramID, float newValue)
{
    if (! pageReady)
        return;

    // Forward every parameter change to JS in real time.
    // Keep the object on the message thread (parameterChanged may be called
    // from the audio thread on some hosts).
    juce::MessageManager::callAsync ([this, paramID, newValue]
    {
        if (! pageReady)
            return;
        webView.emitEventIfBrowserIsVisible ("paramChange",
            makeObj ({ { "id", paramID }, { "value", newValue } }));

        // Rebuild the engine snapshot for the affected lane.  setValueNotifyingHost
        // updates the APVTS atomic but the audio thread reads from a separate
        // LaneSnapshot struct that's only refreshed when updateLaneSnapshot()
        // is called explicitly.  Without this hop, every per-lane parameter
        // change (quantize, divisions, range, smoothing, msgType, etc.)
        // updates the UI and the APVTS, but the actual MIDI output keeps
        // using the previous snapshot — which is exactly the symptom the
        // user reported with the quantization buttons.
        //
        // The native editor (PluginEditor.cpp) called updateLaneSnapshot()
        // from its slider attachments; the WebUI editor needs the equivalent
        // here, since its only parameter-change pipeline is the bridge.
        if (paramID.startsWith ("l"))
        {
            const int sep = paramID.indexOfChar ('_');
            if (sep > 1)
            {
                const int lane = paramID.substring (1, sep).getIntValue();
                if (lane >= 0 && lane < kMaxLanes)
                    proc.updateLaneSnapshot (lane);
            }
        }
    });
}

// ── State snapshot ────────────────────────────────────────────────────────────

void WebCurveEditor::sendStateSnapshot()
{
    // Build a complete state object and emit it so the JS can initialise
    // its React state from real APVTS values instead of the demo sine curves.

    juce::var lanesArr (juce::Array<juce::var>{});
    auto& lanesArrRef = *lanesArr.getArray();

    for (int L = 0; L < proc.activeLaneCount; ++L)
    {
        auto lane = std::make_unique<juce::DynamicObject>();

        lane->setProperty ("id",    L);
        lane->setProperty ("name",  "Lane " + juce::String (L + 1));

        // APVTS helpers.
        // getRawParameterValue returns ACTUAL values (not 0-1 normalised):
        //   AudioParameterChoice → choice index (0, 1, 2 …)
        //   AudioParameterInt    → integer value in its declared range
        //   AudioParameterFloat  → float in its declared range (smoothing/minOut/maxOut are 0-1)
        //   AudioParameterBool   → 0.0f or 1.0f
        const auto raw = [&] (const juce::String& suffix) -> float {
            if (auto* p = proc.apvts.getRawParameterValue (laneParam (L, suffix)))
                return p->load();
            jassertfalse;   // parameter ID not registered — check laneParam() format
            return 0.0f;
        };

        // scaleRoot / scaleMask are global (shared by all lanes) — no lane prefix.
        const auto globalRaw = [&] (const juce::String& id) -> float {
            if (auto* p = proc.apvts.getRawParameterValue (id))
                return p->load();
            jassertfalse;
            return 0.0f;
        };

        static const char* kTargets[4] = { "CC", "Aftertouch", "PitchBend", "Note" };
        const int msgType = juce::jlimit (0, 3, static_cast<int> (raw ("msgType")));
        lane->setProperty ("target",       kTargets[msgType]);
        lane->setProperty ("targetDetail", static_cast<int> (raw ("ccNumber")));   // 0-127
        lane->setProperty ("channel",      static_cast<int> (raw ("midiChannel")));// 1-16
        lane->setProperty ("smooth",       raw ("smoothing"));                     // 0-1
        lane->setProperty ("rangeMin",     raw ("minOutput"));                     // 0-1
        lane->setProperty ("rangeMax",     raw ("maxOutput"));                     // 0-1
        lane->setProperty ("velocity",     static_cast<int> (raw ("noteVelocity")));// 1-127
        lane->setProperty ("enabled",      raw ("enabled") > 0.5f);
        // Per-lane quantization (mirrors xQuantize/yQuantize/xDivisions/yDivisions APVTS).
        lane->setProperty ("quantizeX",    raw ("xQuantize") > 0.5f);
        lane->setProperty ("quantizeY",    raw ("yQuantize") > 0.5f);
        lane->setProperty ("xDivisions",   static_cast<int> (raw ("xDivisions")));   // 2-32
        lane->setProperty ("yDivisions",   static_cast<int> (raw ("yDivisions")));   // 2-24
        lane->setProperty ("scaleRoot",    static_cast<int> (globalRaw (ParamID::scaleRoot)));  // 0-11
        lane->setProperty ("scaleMask",    static_cast<int> (globalRaw (ParamID::scaleMask)));  // 0-4095
        lane->setProperty ("scaleId",      "chromatic");   // TODO: derive from mask

        // Curve data (Float32Array → JSON array of 256 floats)
        if (proc.hasCurve (L))
        {
            juce::var curveArr (juce::Array<juce::var>{});
            auto& ref = *curveArr.getArray();
            ref.resize (256);
            const auto table = proc.getCurveTable (L);
            for (int i = 0; i < 256; ++i)
                ref.set (i, table[static_cast<std::size_t> (i)]);
            lane->setProperty ("curve", curveArr);
        }
        else
        {
            lane->setProperty ("curve", juce::var());   // null
        }

        lanesArrRef.add (juce::var (lane.release()));
    }

    const auto snap = makeObj ({
        { "lanes",           lanesArr },
        { "activeLaneCount", proc.activeLaneCount },
        { "phase",           proc.currentPhase() },
        { "playing",         true },
        { "direction",       "fwd" },
        { "syncOn",          true },
        { "beats",           4 },
        { "speed",           1.0 },
        { "focus",           0 },
    });

    webView.emitEventIfBrowserIsVisible ("stateSnapshot", snap);
}

void WebCurveEditor::sendCurveData (int lane)
{
    if (!proc.hasCurve (lane)) return;

    juce::var arr (juce::Array<juce::var>{});
    auto& ref = *arr.getArray();
    ref.resize (256);
    const auto table = proc.getCurveTable (lane);
    for (int i = 0; i < 256; ++i)
        ref.set (i, table[static_cast<std::size_t> (i)]);

    webView.emitEventIfBrowserIsVisible ("curveData",
        makeObj ({ { "lane", lane }, { "data", arr } }));
}
